"""init

Revision ID: 3e9a0867b4fa
Revises: 
Create Date: 2026-02-07 17:12:43.543178
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '3e9a0867b4fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('locality', sa.String(length=128), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('precision_level', sa.Enum('exact', 'locality', 'region', name='location_precision_level'), nullable=False),
    sa.Column('provider', sa.Enum('yandex', 'dadata', 'osm', 'manual', name='location_provider'), nullable=True),
    sa.Column('provider_place_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moderation_reasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('styles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('client', 'master', 'moderator', name='user_role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('appeals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appellant_user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('moderation_action', 'user_restriction', 'complaint', 'sketch', 'message', name='appeal_target_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'in_review', 'approved', 'rejected', 'closed', name='appeal_status'), server_default='submitted', nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by_moderator_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['appellant_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_moderator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Enum('mobile', 'web', 'admin', 'system', name='audit_source'), nullable=False),
    sa.Column('ip_hash', sa.String(length=128), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('chat_kind', sa.Enum('direct', name='chat_kind'), server_default='direct', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('collection_type', sa.Enum('portfolio', 'materials', 'process', 'find_us', 'achievments', 'likes', 'custom', name='collection_type'), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('user', 'sketch', 'message', name='complaint_target_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_review', 'resolved', 'rejected', name='complaint_status'), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_preferred_styles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('style_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'style_id')
    )
    op.create_table('feed_preferred_tags',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    op.create_table('inkmatch_defaults',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experience_years_min', sa.Integer(), nullable=True),
    sa.Column('rating_min', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('workplace', sa.Enum('studio', 'home', 'any', name='workplace_type'), nullable=True),
    sa.Column('search_mode', sa.Enum('city', 'region', 'radius', name='search_mode'), server_default='city', nullable=False),
    sa.Column('city_location_id', sa.UUID(), nullable=True),
    sa.Column('region_location_id', sa.UUID(), nullable=True),
    sa.Column('radius_meters', sa.Integer(), nullable=True),
    sa.Column('center_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('center_lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('default_size_sm', sa.Integer(), nullable=True),
    sa.Column('default_price_min', sa.Integer(), nullable=True),
    sa.Column('default_price_max', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['region_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('master_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('price_min', sa.Integer(), nullable=True),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), server_default='0', nullable=False),
    sa.Column('completed_sessions_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('master_verification_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('master_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'in_review', 'approved', 'rejected', name='verification_status'), server_default='draft', nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_moderator_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_moderator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metro_stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_location_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('line_name', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['city_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moderation_queue_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('complaint', 'verification', 'new_post', 'message_report', 'appeal', 'suspicious_case', name='moderation_queue_entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), server_default='3', nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', name='moderation_queue_status'), server_default='open', nullable=False),
    sa.Column('assigned_moderator_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_moderator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('message', 'inkmatch', 'session', 'moderation', 'system', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('home_location_id', sa.UUID(), nullable=True),
    sa.Column('default_currency', sa.String(length=3), server_default='RUB', nullable=False),
    sa.ForeignKeyConstraint(['home_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('sketches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.Enum('sketch', 'final_work', 'process', 'portfolio', 'achievments', 'find_us', 'materials', name='sketch_content_type'), nullable=False),
    sa.Column('feed_visibility', sa.String(length=32), server_default='public', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('original_author_type', sa.Enum('self_', 'other', 'unknown', name='original_author_type'), server_default='unknown', nullable=False),
    sa.Column('original_author_name', sa.String(length=255), nullable=True),
    sa.Column('original_source_url', sa.String(length=512), nullable=True),
    sa.Column('original_author_user_id', sa.UUID(), nullable=True),
    sa.Column('like_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reviewed', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_author_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followed_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('user_restrictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('imposed_by_moderator_id', sa.UUID(), nullable=False),
    sa.Column('restriction_type', sa.Enum('full_block', 'chat_only_read', 'posting_disabled', 'commenting_disabled', 'inkmatch_disabled', 'profile_hidden', name='restriction_type'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('reason_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imposed_by_moderator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reason_id'], ['moderation_reasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appeal_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appeal_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.Enum('image', 'video', 'document', 'other', name='appeal_file_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appeal_id'], ['appeals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_event_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_event_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audit_event_id'], ['audit_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_participants',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.create_table('collection_items',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('sketch_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('work_duration_houres', sa.Integer(), nullable=True),
    sa.Column('work_price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['sketch_id'], ['sketches.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'sketch_id')
    )
    op.create_table('inkmatch_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_by_role', sa.Enum('client', 'master', name='request_creator_role'), nullable=False),
    sa.Column('sketch_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'matched', 'cancelled', 'deleted', name='inkmatch_request_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sketch_id'], ['sketches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_verification_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('id', 'passport', 'certificate', 'diploma', 'award', 'other', name='verification_document_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['master_verification_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_verification_personal_data',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('second_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('patronymic', sa.String(length=64), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('citizenship', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['master_verification_requests.id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('master_workplaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('master_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('is_home_studio', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('studio_name', sa.String(length=255), nullable=True),
    sa.Column('public_display_mode', sa.Enum('city_only', 'street', 'metro', 'full_address', name='workplace_display_mode'), server_default='street', nullable=False),
    sa.Column('public_metro_station_id', sa.UUID(), nullable=True),
    sa.Column('public_text_override', sa.String(length=255), nullable=True),
    sa.Column('show_on_map', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('public_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('public_lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['public_metro_station_id'], ['metro_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moderation_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('warn', 'block_user', 'apply_restriction', 'remove_content', 'restore_content', 'resolve_complaint', name='moderation_action_type'), nullable=False),
    sa.Column('target_type', sa.Enum('user', 'sketch', 'message', name='moderation_target_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sketch_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sketch_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['sketch_comments.id'], ),
    sa.ForeignKeyConstraint(['sketch_id'], ['sketches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sketch_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sketch_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', name='media_type'), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('preview_image_url', sa.String(length=512), nullable=True),
    sa.Column('duration_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('phash', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sketch_id'], ['sketches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sketch_styles',
    sa.Column('sketch_id', sa.UUID(), nullable=False),
    sa.Column('style_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sketch_id'], ['sketches.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.PrimaryKeyConstraint('sketch_id', 'style_id')
    )
    op.create_table('sketch_tags',
    sa.Column('sketch_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sketch_id'], ['sketches.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('sketch_id', 'tag_id')
    )
    op.create_table('client_inkmatch_params',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('size_sm', sa.Integer(), nullable=True),
    sa.Column('price_min', sa.Integer(), nullable=True),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('search_mode', sa.Enum('city', 'region', 'radius', name='client_search_mode'), nullable=False),
    sa.Column('city_location_id', sa.UUID(), nullable=True),
    sa.Column('region_location_id', sa.UUID(), nullable=True),
    sa.Column('center_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('center_lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('radius_meters', sa.Integer(), nullable=True),
    sa.Column('preferred_experience_years_min', sa.Integer(), nullable=True),
    sa.Column('preferred_rating_min', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('preferred_workplace', sa.Enum('studio', 'home', 'any', name='preferred_workplace'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['region_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['inkmatch_requests.id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('comments_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.Enum('image', 'video', 'document', 'other', name='comment_file_type'), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['sketch_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inkmatches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sketch_id', sa.UUID(), nullable=False),
    sa.Column('client_request_id', sa.UUID(), nullable=False),
    sa.Column('master_request_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', 'cancelled', name='inkmatch_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_request_id'], ['inkmatch_requests.id'], ),
    sa.ForeignKeyConstraint(['master_request_id'], ['inkmatch_requests.id'], ),
    sa.ForeignKeyConstraint(['sketch_id'], ['sketches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_inkmatch_offer',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('offer_price', sa.Integer(), nullable=False),
    sa.Column('offer_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['inkmatch_requests.id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('master_verification_document_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['master_verification_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.Enum('image', 'video', 'document', 'other', name='message_file_type'), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sketch_comment_likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['sketch_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    op.create_table('sketch_pins',
    sa.Column('sketch_id', sa.UUID(), nullable=False),
    sa.Column('pinned_comment_id', sa.UUID(), nullable=False),
    sa.Column('pinned_by_user_id', sa.UUID(), nullable=False),
    sa.Column('pinned_reason', sa.String(length=64), server_default='inkmatch_review', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pinned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pinned_comment_id'], ['sketch_comments.id'], ),
    sa.ForeignKeyConstraint(['sketch_id'], ['sketches.id'], ),
    sa.PrimaryKeyConstraint('sketch_id')
    )
    op.create_table('inkmatch_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inkmatch_id', sa.UUID(), nullable=False),
    sa.Column('rating_overall', sa.SmallInteger(), nullable=False),
    sa.Column('rating_communication', sa.SmallInteger(), nullable=False),
    sa.Column('rating_cleanliness', sa.SmallInteger(), nullable=False),
    sa.Column('rating_quality', sa.SmallInteger(), nullable=False),
    sa.Column('rating_punctuality', sa.SmallInteger(), nullable=False),
    sa.Column('rating_price_fairness', sa.SmallInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inkmatch_id'], ['inkmatches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inkmatch_id', name='uq_inkmatch_review_inkmatch')
    )
    op.create_table('inkmatch_review_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.Enum('image', 'video', 'document', 'other', name='inkmatch_review_file_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['inkmatch_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inkmatch_review_attachments')
    op.drop_table('inkmatch_reviews')
    op.drop_table('sketch_pins')
    op.drop_table('sketch_comment_likes')
    op.drop_table('message_attachments')
    op.drop_table('master_verification_document_files')
    op.drop_table('master_inkmatch_offer')
    op.drop_table('inkmatches')
    op.drop_table('comments_attachments')
    op.drop_table('client_inkmatch_params')
    op.drop_table('sketch_tags')
    op.drop_table('sketch_styles')
    op.drop_table('sketch_media')
    op.drop_table('sketch_comments')
    op.drop_table('notification_links')
    op.drop_table('moderation_actions')
    op.drop_table('messages')
    op.drop_table('master_workplaces')
    op.drop_table('master_verification_personal_data')
    op.drop_table('master_verification_documents')
    op.drop_table('inkmatch_requests')
    op.drop_table('collection_items')
    op.drop_table('chat_participants')
    op.drop_table('audit_event_targets')
    op.drop_table('appeal_attachments')
    op.drop_table('user_restrictions')
    op.drop_table('subscriptions')
    op.drop_table('sketches')
    op.drop_table('refresh_tokens')
    op.drop_table('profiles')
    op.drop_table('notifications')
    op.drop_table('moderation_queue_items')
    op.drop_table('metro_stations')
    op.drop_table('master_verification_requests')
    op.drop_table('master_profiles')
    op.drop_table('inkmatch_defaults')
    op.drop_table('feed_preferred_tags')
    op.drop_table('feed_preferred_styles')
    op.drop_table('complaints')
    op.drop_table('collections')
    op.drop_table('chats')
    op.drop_table('audit_events')
    op.drop_table('appeals')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('styles')
    op.drop_table('moderation_reasons')
    op.drop_table('locations')
    # ### end Alembic commands ###
